# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MIX_ENV: test
    
permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: [1.14.0, 1.15.2]
        otp: [25.13.2, 26.0]

    steps:
      - uses: actions/checkout@v3

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
          otp-version: ${{ matrix.otp }} # Define the OTP version [required]
          
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --forces
          mix local.hex --force
          mix deps.get
      
      - name: Check Formatting
        run: mix format --check-formatted
        
      - name: Run Credo
        run: mix credo --strict
        
      - name: Run tests
        run: mix test
